class CourseAI:
    def build(self):
        return """<?php
$course = [
  "title" => "Digital Skills for Moms",
  "lessons" => [
    "Using WhatsApp for Business",
    "Facebook Marketing Basics",
    "Online Safety",
    "Making Money Online"
  ]
];

file_put_contents("courses_generated.txt", json_encode($course));
echo "Course generated by AI";
?>"""
